language: python
python:
- 3.8.1
before_script:
- python --version
- pip install -r requirements.txt
script:
- |
  if [ $TRAVIS_PULL_REQUEST == true ] && [ $TRAVIS_BRANCH != "master" ]; then
    VERSION="v$(cat main/root.template | shyaml get-value Globals.Function.Environment.Variables.VERSION)"
    git tag $VERSION
  fi
before_deploy:
- VERSION="v$(cat main/root.template | shyaml get-value Globals.Function.Environment.Variables.VERSION)"
- if [ -z "$TRAVIS_TAG" ]; then git tag $VERSION; fi
- zip -r "$VERSION.zip" -@ < ci/include.lst
deploy:
- provider: releases
  api_key:
    secure: qHZuawzAA7/kqBAauD35Tf0l2OCOnmLlUJMFBNyi/vBdJ/tjCnHvdxBR0c+hcW8qegMy5pdlE9ERLV8liKWD1+xg2X94rQuQYuFaT1Eof+hdJjlw1OPjpcHHJ64K1mpLtwrGbn4e32xSazptvjdydDAmUssK85mQEXZ0GMJb1iV9qBmaUM4b2UW38VG27dK4QircSx9Ych17Y7AHqm+XSB64RrHX5OpnufJ+2rSWgqXXJOvFGnehlnqynzYAFwEaOH+ayYeZz8xFEwWt+zeK2kJUWDyswZ3ZJjngkNkFUJk9CbiubarYOGfKqeVgnXyxwS2+XuI49QIqw6nJ4ptD6rJ2iPA+WMEZtr82jKZ+AbR/LNfM7ARaGdb+R+xBz9uVQ50p8/EdnZ3sxEpdo/h14UQ1/qXhiu7QZJYsTp7jr9+oHGWnCtAMUVlXYDOrRG0orxZKwTBnF3jGmWGDmAMc/3FsIe66ZCkI7wTYZBkolUyIuH7VasG2JH698tucQETJWuKbT9r7JvwFahBBhDW/Ks88nRHwG2Welx5ltXp23aflU/EaHpDd+DBgMV+nb05ectQURdOsWpPYkbDhdARhoCtqryqJoxHTo45xAjsME3t1ijlcnYhrZSsVDQ9IZ5RbGKFw0KRpZy46wfrIHYdXcRu+Fl6bcEmq7vWw8Sh4a3Y=
  file: "$VERSION.zip"
  skip_cleanup: true
  on:
    branch: master
    condition: type != pull_request
- provider: script
  script: aws s3 cp ./$VERSION.zip s3://$CFN_BUCKET/aws-digital-content-creation-render-environment/$VERSION/aws-digital-content-creation-render-environment.zip
  skip_cleanup: true
  on:
    tags: true
notifications:
  email: false
cache: pip
